import { compileSearch } from "@/domain/engine"; import { TransformationSearchQuery } from "@/domain/schemas"; import { supabaseConfigured } from "@/lib/supabase/config"; import { createSupabaseServerClient } from "@/lib/supabase/server"; import { planSearch } from "@/research/services";
export type ResearchRunSummary={id:string;status:string;researchType:string;startedAt:string;summary:string|null;totalTasks:number;completeTasks:number;queuedTasks:number};
export type ResearchPublication={id:string;title:string;publicationDate:string|null;pmid:string;doi:string;authors:string[];providerUrl:string;normalizationVersion:string};
export type ResearchTaskDetail={id:string;agentType:string;objective:string;status:string;attemptCount:number;startedAt:string|null;completedAt:string|null;error:string|null;input:Record<string,unknown>;output:Record<string,unknown>|null;publications:ResearchPublication[]};
export type ResearchRunDetail={id:string;status:string;researchType:string;startedAt:string;completedAt:string|null;summary:string|null;researchPlan:Record<string,unknown>;modelConfiguration:Record<string,unknown>;budgetConfiguration:Record<string,unknown>;tasks:ResearchTaskDetail[]};
export function summarizeTaskCounts(tasks:{research_run_id:string;status:string}[]){const counts=new Map<string,{totalTasks:number;completeTasks:number;queuedTasks:number}>();for(const task of tasks){const value=counts.get(task.research_run_id)??{totalTasks:0,completeTasks:0,queuedTasks:0};value.totalTasks++;if(task.status==="complete")value.completeTasks++;if(task.status==="queued")value.queuedTasks++;counts.set(task.research_run_id,value)}return counts}
export async function listResearchRuns():Promise<ResearchRunSummary[]>{const db=await createSupabaseServerClient();const {data:runs,error:runError}=await db.from("research_runs").select("id,status,research_type,started_at,summary").order("started_at",{ascending:false});if(runError)throw new Error(runError.message);const {data:tasks,error:taskError}=await db.from("research_tasks").select("research_run_id,status");if(taskError)throw new Error(taskError.message);const counts=summarizeTaskCounts(tasks??[]);return (runs??[]).map(run=>({id:run.id,status:run.status,researchType:run.research_type,startedAt:run.started_at,summary:run.summary,...(counts.get(run.id)??{totalTasks:0,completeTasks:0,queuedTasks:0})}))}
export async function getResearchRunDetail(id:string):Promise<ResearchRunDetail>{const db=await createSupabaseServerClient();const {data,error}=await db.rpc("get_research_run_detail",{p_run_id:id});if(error)throw new Error(error.message);return data as ResearchRunDetail}
export async function createResearchRun(query:TransformationSearchQuery){if(!supabaseConfigured())throw new Error("Research-run persistence requires a configured Supabase project.");const db=await createSupabaseServerClient();const {data:{user}}=await db.auth.getUser();if(!user)throw new Error("Authentication required");const compiled=compileSearch(query);const {data:search,error:searchError}=await db.from("search_runs").insert({name:`Structured search ${new Date().toISOString()}`,minimum_human_validation:query.minimumHumanValidation,causal_mechanism_filter:undefined,minimum_therapeutic_delta:query.minimumTherapeuticDelta,minimum_technical_feasibility:query.minimumTechnicalFeasibility,minimum_independent_targets:query.minimumIndependentTargets,minimum_lead_quality_opportunities:query.minimumLeadQualityOpportunities,exclusions:query.exclusions,ranking_criteria:query.rankingCriteria,evidence_standard:query.evidenceStandard,compiled_prompt:compiled,status:"planned",created_by_user_id:user.id}).select("id").single();if(searchError)throw new Error(searchError.message);const plan=planSearch(search.id,query);const {data:run,error:runError}=await db.from("research_runs").insert({search_run_id:search.id,research_type:"landscape_search",status:"planned",research_plan:plan,started_at:new Date().toISOString(),initiated_by_type:"human",initiated_by_user_id:user.id,model_configuration:{provider:"unconfigured"},budget_configuration:{maxSources:20,maxSearchIterations:3,maxAgentSteps:12,maxModelCalls:8,minimumConfidenceBeforeStopping:"B"},summary:"Structured research run created; awaiting provider execution."}).select("id").single();if(runError)throw new Error(runError.message);const tasks=plan.phases.map((phase,index)=>({research_run_id:run.id,agent_type:["mechanism_validation","entity_resolution","constraint_discovery","causality","transformation_matching","contrary_evidence","diligence"][Math.min(index,6)],objective:phase.objective,input_payload:{queries:phase.queries,dataSources:phase.dataSources,expectedOutput:phase.expectedOutput},status:"queued",attempt_count:0}));const {error:taskError}=await db.from("research_tasks").insert(tasks);if(taskError)throw new Error(taskError.message);return {searchRunId:search.id,researchRunId:run.id,status:"planned",compiledPrompt:compiled,taskCount:tasks.length}}
