import { hashPayload } from "@/research/services"; import { NormalizedScientificRecord, RawScientificRecord, ScientificDataAdapter, ScientificSearchQuery, SearchResult } from "@/research/types";
const api="https://eutils.ncbi.nlm.nih.gov/entrez/eutils"; const tool="asset-transformation-engine";
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function ncbi(url:string){for(let attempt=0;attempt<3;attempt++){const response=await fetch(url,{headers:{"user-agent":"AssetTransformationEngine/0.1 (research prototype)"},cache:"no-store"});if(response.ok)return response.json();if(response.status!==429||attempt===2)throw new Error(`PubMed request failed (${response.status})`);const retryAfter=Number(response.headers.get("retry-after")??0);await wait(retryAfter>0?retryAfter*1000:500*(attempt+1))}throw new Error("PubMed request failed")}
export class PubMedAdapter implements ScientificDataAdapter{provider="pubmed";async search(query:ScientificSearchQuery):Promise<SearchResult[]>{const url=`${api}/esearch.fcgi?db=pubmed&retmode=json&retmax=${Math.min(query.limit,20)}&tool=${tool}&term=${encodeURIComponent(query.query)}`;const result=await ncbi(url);const ids=(result.esearchresult?.idlist??[]) as string[];return ids.map(identifier=>({identifier,title:`PubMed ${identifier}`,recordType:"publication",providerUrl:`https://pubmed.ncbi.nlm.nih.gov/${identifier}/`}))}async fetchMany(identifiers:string[]):Promise<RawScientificRecord[]>{if(identifiers.some(identifier=>!/^\d+$/.test(identifier)))throw new Error("PubMed identifiers must be numeric");if(!identifiers.length)return [];const [payload,xml]=await Promise.all([ncbi(`${api}/esummary.fcgi?db=pubmed&retmode=json&tool=${tool}&id=${identifiers.join(",")}`),ncbiText(`${api}/efetch.fcgi?db=pubmed&retmode=xml&tool=${tool}&id=${identifiers.join(",")}`)]);const abstracts=parsePubMedAbstracts(xml);return identifiers.map(identifier=>{const summary=payload.result?.[identifier];if(!summary)throw new Error(`PubMed record ${identifier} was not found`);const record={...summary,abstract:abstracts[identifier]};return {provider:this.provider,providerRecordId:identifier,providerUrl:`https://pubmed.ncbi.nlm.nih.gov/${identifier}/`,recordType:"publication",rawPayload:record,retrievedAt:new Date().toISOString(),contentHash:hashPayload(record)}})}async fetch(identifier:string):Promise<RawScientificRecord>{return (await this.fetchMany([identifier]))[0]}async normalize(record:RawScientificRecord):Promise<NormalizedScientificRecord>{const r=record.rawPayload;return {id:`pubmed-${record.providerRecordId}`,rawRecordId:record.providerRecordId,normalizedType:"publication",title:String(r.title??`PubMed ${record.providerRecordId}`),abstractOrSummary:typeof r.abstract==="string"?r.abstract:undefined,publicationDate:normalizePubDate(String(r.pubdate??"")),identifiers:{pmid:record.providerRecordId,doi:findArticleId(r.articleids,"doi")??""},authors:Array.isArray(r.authors)?r.authors.map((a:unknown)=>String((a as {name?:string}).name??"")).filter(Boolean):[],organizations:[],normalizedPayload:r,normalizationVersion:"pubmed-abstract-v2"}}}
async function ncbiText(url:string){for(let attempt=0;attempt<3;attempt++){const response=await fetch(url,{headers:{"user-agent":"AssetTransformationEngine/0.1 (research prototype)"},cache:"no-store"});if(response.ok)return response.text();if(response.status!==429||attempt===2)throw new Error(`PubMed request failed (${response.status})`);await wait(500*(attempt+1))}throw new Error("PubMed request failed")}
export function parsePubMedAbstracts(xml:string){const result:Record<string,string>={};for(const article of xml.match(/<PubmedArticle>[\s\S]*?<\/PubmedArticle>/g)??[]){const pmid=article.match(/<PMID[^>]*>(\d+)<\/PMID>/)?.[1];if(!pmid)continue;const parts=[...article.matchAll(/<AbstractText[^>]*>([\s\S]*?)<\/AbstractText>/g)].map(match=>decodeXml(match[1].replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim())).filter(Boolean);if(parts.length)result[pmid]=parts.join(" ")}return result}
function decodeXml(value:string){return value.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'")}
function findArticleId(value:unknown,type:string){if(!Array.isArray(value))return undefined;return value.find(x=>(x as {idtype?:string}).idtype===type)?.value as string|undefined}function normalizePubDate(value:string){const match=value.match(/^(\d{4})(?:\s+(\w{3}))?(?:\s+(\d{1,2}))?/);if(!match)return undefined;const month=match[2]?String(["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"].indexOf(match[2])+1).padStart(2,"0"):"01";return `${match[1]}-${month}-${String(match[3]??"01").padStart(2,"0")}`}
