export const confidenceOrder = { X: 0, D: 1, C: 2, B: 3, A: 4 } as const;
export type ConfidenceGrade = keyof typeof confidenceOrder;
export type GateStatus = "NOT_EVALUATED" | "PASS" | "HOLD" | "FAIL";
export type OpportunityStage = "transformation_hypothesis" | "gated_opportunity" | "asset_opportunity" | "lead_candidate" | "archived" | "killed";
export type Recommendation = "kill" | "hold" | "watch" | "investigate" | "advance" | "partner" | "build";

export interface Criterion { code: string; name: string; description: string; weight: number; isGate: boolean; gateThreshold?: number; minimumConfidence?: ConfidenceGrade; }
export interface Assessment { id: string; criterionCode: string; score: number; confidence: ConfidenceGrade; rationale: string; assessorType: "human" | "ai"; assessorName: string; evidenceSupporting: string[]; evidenceContradicting: string[]; createdAt: string; }
export interface GateAssessment extends Assessment { gateStatus: GateStatus; }
export interface ThesisParts { mechanism: string | null; context: string | null; constraint: string | null; causalMechanism: string | null; transformation: string | null; drugProperty: string | null; clinicalAdvantage: string | null; }
export interface TransformationThesis extends ThesisParts { complete: boolean; renderedText: string | null; }
export interface KillerAssumption { id: string; statement: string; category: string; criticality: "fatal" | "major" | "moderate"; confidence: ConfidenceGrade; status: "untested" | "partially_supported" | "supported" | "refuted"; falsificationConsequence: string; bestTest: string; nextBestEvidence?: string; }
export interface DiligenceAction { id: string; question: string; actionType: string; priority: number; expectedInformationGain: string; status: "open" | "in_progress" | "complete"; }
export interface EvidenceClaim { id: string; claimText: string; relationship: "supports" | "contradicts" | "context"; source: string; sourceType: string; evidenceLevel: number; extractionConfidence: ConfidenceGrade; humanVerified: boolean; sourceLocator?: string; }
export interface ArchitectureComponent { type: string; name: string; description: string; }
export interface StageTransition { from: OpportunityStage | null; to: OpportunityStage; reason: string; triggeredBy: string; createdAt: string; }
export interface OpportunityDTO { id: string; slug: string; name: string; mechanism: string; target: string; indication: string; therapeuticArea: string; constraint: string; constraintType: string; causalMechanism: string; transformation: string; transformationFamily: string; drugProperty: string; clinicalAdvantage: string; stage: OpportunityStage; recommendation: Recommendation; thesis: TransformationThesis; overallGateStatus: GateStatus; score: number | null; confidence: ConfidenceGrade; sensitivityLow: number | null; sensitivityHigh: number | null; assessments: Assessment[]; strongestSupportingArgument: string; strongestDisconfirmingArgument: string; whyMightWeBeWrong: string; alternativeExplanations: string[]; architecture: ArchitectureComponent[]; assumptions: KillerAssumption[]; diligenceActions: DiligenceAction[]; evidence: EvidenceClaim[]; familyId?: string; familyName?: string; familyTier?: string; transitions: StageTransition[]; illustrative: true; }
export interface FamilyMember { opportunityId: string; tier: "tier_1_lead" | "tier_2_pipeline" | "tier_3_expansion" | "tier_4_speculative"; isDesignatedLead: boolean; rationale: string; }
export interface OpportunityFamilyDTO { id: string; slug: string; name: string; transformation: string; engineeringPrimitive: string; sharedConstraint: string; thesis: string; stage: "forming" | "opportunity_family" | "spinco_candidate" | "priority_spinco"; recommendation: Recommendation; members: FamilyMember[]; independentTargetCount: number; tier1Count: number; score: number; confidence: ConfidenceGrade; assessments: Assessment[]; whyNow: string; whyNotAlready: string; whyThisCompany: string; whatCompounds: string; strongestArgument: string; strongestObjection: string; illustrative: true; }
