import { z } from "zod";
const confidence=z.enum(["A","B","C","D","X"]); const claimId=z.string().min(1);
export const extractedClaimSchema=z.object({id:z.string(),claimText:z.string().min(8),claimType:z.string().min(1),entities:z.array(z.object({type:z.string(),canonicalEntityId:z.string().optional(),rawName:z.string()})),context:z.object({indicationId:z.string().optional(),population:z.string().optional(),dose:z.string().optional(),timepoint:z.string().optional(),comparator:z.string().optional()}),quantitativeData:z.array(z.object({metric:z.string(),value:z.number().optional(),unit:z.string().optional(),comparatorValue:z.number().optional(),statisticalContext:z.string().optional()})).optional(),evidenceLevel:z.number().int().min(1).max(5),directness:z.enum(["direct","indirect","inferred"]),species:z.enum(["human","nonhuman_primate","mouse","other_animal","in_vitro","unknown"]),sourceLocator:z.string().optional(),excerpt:z.string().optional(),extractionConfidence:confidence,evidenceClusterId:z.string().optional()});
export const mechanismValidationSchema=z.object({mechanismContextId:z.string(),proposedScore:z.number().int().min(0).max(5),proposedConfidence:confidence,supportingEvidenceClaimIds:z.array(claimId),contradictingEvidenceClaimIds:z.array(claimId),rationale:z.string(),unresolvedQuestions:z.array(z.string())});
export const constraintDiscoverySchema=z.object({classification:z.enum(["likely_biology_limitation","likely_drug_property_limitation","mixed","unclear"]),constraintType:z.string(),clinicalManifestation:z.string(),affectedAssetIds:z.array(z.string()),severityHypothesis:z.number().min(0).max(5),supportingEvidenceClaimIds:z.array(claimId),contradictingEvidenceClaimIds:z.array(claimId),possibleCausalMechanisms:z.array(z.string()),confidence, evidenceGaps:z.array(z.string())});
export const causalitySchema=z.object({constraintId:z.string(),primaryCausalHypothesis:z.string(),affectedDrugPropertyIds:z.array(z.string()),alternativeExplanations:z.array(z.object({explanation:z.string(),confidence,evidenceClaimIds:z.array(claimId)})),proposedScore:z.number().min(0).max(5),proposedConfidence:confidence,strongestSupportingEvidence:z.array(claimId),strongestContradictingEvidence:z.array(claimId),nextBestEvidence:z.string()});
export const transformationCandidateSchema=z.object({transformationId:z.string(),constraintId:z.string(),intendedDrugPropertyIds:z.array(z.string()),expectedClinicalAdvantageIds:z.array(z.string()),rationale:z.string(),prerequisiteChecks:z.array(z.object({requirement:z.string(),isCritical:z.boolean(),status:z.enum(["supported","partially_supported","unknown","contradicted"]),confidence,evidenceClaimIds:z.array(claimId)})),proposedTransformationFit:z.number().min(0).max(5),proposedConfidence:confidence});
export const contraryEvidenceSchema=z.object({opportunityId:z.string(),strongestObjections:z.array(z.object({objection:z.string(),severity:z.enum(["fatal","major","moderate","minor"]),evidenceClaimIds:z.array(claimId)})),historicalFailures:z.array(z.string()),unresolvedThreats:z.array(z.string()),suggestedKillTests:z.array(z.string())});
export const assessmentProposalSchema=z.object({id:z.string(),criterionCode:z.string(),targetEntityId:z.string(),proposedScore:z.number().min(0).max(5),proposedConfidence:confidence,baselineConfidence:confidence,confidenceDerivation:z.array(z.string()),rationale:z.string(),supportingEvidenceClaimIds:z.array(claimId),contradictingEvidenceClaimIds:z.array(claimId),status:z.enum(["pending","accepted","modified","rejected"])});
