import { createHash } from "node:crypto"; import { ConfidenceGrade, confidenceOrder, GateStatus } from "@/domain/types"; import { TransformationSearchQuery } from "@/domain/schemas"; import { extractedClaimSchema } from "./schemas"; import { CriticalPrerequisite, EntityAlias, EntityResolutionResult, ExtractedEvidenceClaim, NormalizedScientificRecord, RawScientificRecord, ResearchBudget, ResearchPlan, ScientificDataAdapter, ScientificSearchQuery, SearchResult } from "./types";

export function hashPayload(value:unknown){return createHash("sha256").update(JSON.stringify(value)).digest("hex")}
export class FixtureScientificAdapter implements ScientificDataAdapter{
 provider="curated_fixture_provider"; constructor(private records:Record<string,Record<string,unknown>>){ }
 async search(query:ScientificSearchQuery):Promise<SearchResult[]>{const q=query.query.toLowerCase();return Object.entries(this.records).filter(([,r])=>JSON.stringify(r).toLowerCase().includes(q.split(" ")[0])).slice(0,query.limit).map(([identifier,r])=>({identifier,title:String(r.title),recordType:String(r.type),providerUrl:`fixture://${identifier}`}))}
 async fetch(identifier:string):Promise<RawScientificRecord>{const payload=this.records[identifier];if(!payload)throw new Error(`Unknown fixture record ${identifier}`);return {provider:this.provider,providerRecordId:identifier,providerUrl:`fixture://${identifier}`,recordType:String(payload.type),rawPayload:payload,rawText:String(payload.text??""),retrievedAt:"2026-08-09T12:00:00Z",contentHash:hashPayload(payload)}}
 async normalize(r:RawScientificRecord):Promise<NormalizedScientificRecord>{return {id:`normalized-${r.providerRecordId}`,rawRecordId:r.providerRecordId,normalizedType:r.recordType,title:String(r.rawPayload.title),abstractOrSummary:String(r.rawPayload.summary??r.rawText??""),publicationDate:String(r.rawPayload.publicationDate??""),identifiers:(r.rawPayload.identifiers??{}) as Record<string,string>,authors:(r.rawPayload.authors??[]) as string[],organizations:(r.rawPayload.organizations??[]) as string[],normalizedPayload:r.rawPayload,normalizationVersion:"1.0"}}
}
export class IngestionService{private hashes=new Set<string>();private providerIds=new Set<string>();async ingest(adapter:ScientificDataAdapter,ids:string[]){const imported:NormalizedScientificRecord[]=[];const duplicates:string[]=[];const failures:{id:string;error:string}[]=[];for(const id of ids){try{const raw=await adapter.fetch(id);const key=`${adapter.provider}:${raw.providerRecordId}`;if(this.hashes.has(raw.contentHash)||this.providerIds.has(key)){duplicates.push(id);continue}this.hashes.add(raw.contentHash);this.providerIds.add(key);imported.push(await adapter.normalize(raw))}catch(e){failures.push({id,error:e instanceof Error?e.message:"Unknown error"})}}return {imported,duplicates,failures}}
}
export class EntityResolutionService{resolve(rawValue:string,aliases:EntityAlias[],externalIdentifiers:Record<string,string>={}):EntityResolutionResult{const normalized=rawValue.trim().toLowerCase();const matches=aliases.filter(a=>a.alias.trim().toLowerCase()===normalized||Object.entries(externalIdentifiers).some(([k,v])=>a.externalIdentifiers[k]===v));if(matches.length===1&&confidenceOrder[matches[0].confidence]>=confidenceOrder.B)return {status:"resolved",rawValue,candidateEntityId:matches[0].entityId,normalizedName:matches[0].canonicalName,matchReason:matches[0].alias.toLowerCase()===normalized?"Exact normalized alias":"Shared external identifier",confidence:matches[0].confidence,humanVerified:matches[0].humanVerified};return {status:"unresolved",rawValue,normalizedName:normalized,matchReason:matches.length?"Ambiguous or low-confidence candidates":"No alias or identifier match",confidence:matches.length?"D":"X",humanVerified:false}}
}
export function extractClaims(record:NormalizedScientificRecord):ExtractedEvidenceClaim[]{const claims=Array.isArray(record.normalizedPayload.claims)?record.normalizedPayload.claims:[];return claims.map((c,i)=>extractedClaimSchema.parse({id:`${record.id}-claim-${i+1}`,...c})) as ExtractedEvidenceClaim[]}
export function clusterEvidence(claims:ExtractedEvidenceClaim[]){const groups=new Map<string,ExtractedEvidenceClaim[]>();for(const c of claims){const key=c.evidenceClusterId??c.id;groups.set(key,[...(groups.get(key)??[]),c])}return [...groups.entries()].map(([id,members])=>({id,members,independentCount:1}))}
export function verifyClaimEvidence(conclusion:string,citedIds:string[],claims:ExtractedEvidenceClaim[]):"supported"|"partially_supported"|"unsupported"|"contradicted"{const cited=claims.filter(c=>citedIds.includes(c.id));if(!cited.length)return "unsupported";if(cited.some(c=>c.claimType==="contrary"||c.claimType==="mechanism_failure"))return "contradicted";const terms=new Set(conclusion.toLowerCase().split(/\W+/).filter(x=>x.length>4));const overlap=cited.reduce((n,c)=>n+[...terms].filter(t=>c.claimText.toLowerCase().includes(t)).length,0);return overlap>=Math.max(2,terms.size*.25)?"supported":"partially_supported"}
export function calibrateConfidence(claims:ExtractedEvidenceClaim[]){if(!claims.length)return {grade:"X" as ConfidenceGrade,reasons:["No cited evidence"]};const clusters=new Set(claims.map(c=>c.evidenceClusterId??c.id)).size;const max=Math.max(...claims.map(c=>c.evidenceLevel));const direct=claims.some(c=>c.directness==="direct");const contradictions=claims.filter(c=>c.claimType==="contrary"||c.claimType==="mechanism_failure").length;const grade:ConfidenceGrade=max>=5&&direct&&clusters>=2&&contradictions===0?"A":max>=4&&clusters>=2&&contradictions<=1?"B":max>=3?"C":"D";return {grade,reasons:[`Highest evidence level: ${max}`,`${clusters} independent evidence cluster(s)`,direct?"Includes direct evidence":"Relies on indirect or inferred evidence",contradictions?`${contradictions} contradictory claim(s)`:"No contradiction in cited set"]}}
export function evidenceSufficiency(claims:ExtractedEvidenceClaim[],minimumClusters=1):{sufficient:boolean;confidence:ConfidenceGrade;gate:GateStatus;nextBestEvidence?:string}{const c=calibrateConfidence(claims);const count=new Set(claims.map(x=>x.evidenceClusterId??x.id)).size;if(count<minimumClusters||c.grade==="X")return {sufficient:false,confidence:"X",gate:"HOLD",nextBestEvidence:"Find an independent, directly relevant source and verify an atomic claim."};return {sufficient:true,confidence:c.grade,gate:"NOT_EVALUATED"}}
export const compatibilityRules:Record<string,{constraints:string[];properties:string[];prerequisites:string[]}>= {targeted_delivery:{constraints:["SAFETY_ON_TARGET_OFF_TISSUE","DISTRIBUTION_WRONG_CELL","SELECTIVITY_TISSUE"],properties:["tissue_distribution","cell_distribution","intracellular_exposure"],prerequisites:["Accessible disease-relevant surface antigen","Differential expression","Internalization and productive trafficking","Payload release and retained activity"]},half_life_engineering:{constraints:["PK_SHORT_HALF_LIFE","PK_RAPID_CLEARANCE","ADMIN_FREQUENCY"],properties:["half_life","clearance"],prerequisites:["Current exposure limitation","Longer exposure is clinically valuable","Prolonged exposure does not worsen safety"]},tissue_transport:{constraints:["DISTRIBUTION_CNS"],properties:["cns_exposure"],prerequisites:["CNS-relevant mechanism","Shuttle receptor expression and transport precedent","Pharmacology retained after transport"]},conditional_activation:{constraints:["SAFETY_ON_TARGET_OFF_TISSUE","SAFETY_IMMUNE_TOXICITY"],properties:["conditional_activation","local_activation"],prerequisites:["Disease-specific activation feature","Activation selectivity","Adequate activity after unmasking"]},protein_degradation:{constraints:["RESISTANCE_TARGET_RECOVERY","INCOMPLETE_INHIBITION"],properties:["intracellular_exposure"],prerequisites:["Intracellular target","Degradation advantage over inhibition","Suitable degradation biology","Plausible intracellular access"]}};
export function compatibleTransformations(constraintType:string,property:string){return Object.entries(compatibilityRules).filter(([,r])=>r.constraints.includes(constraintType)&&r.properties.includes(property)).map(([id,r])=>({id,prerequisites:r.prerequisites}))}
export function evaluateCriticalPath(items:CriticalPrerequisite[]){const fatal=items.find(i=>i.isCritical&&i.status==="contradicted"&&confidenceOrder[i.confidence]>=confidenceOrder.B);const unknown=items.filter(i=>i.isCritical&&(i.status==="unknown"||i.confidence==="X"));return fatal?{gate:"FAIL" as GateStatus,maxScore:1,reason:`Critical prerequisite contradicted: ${fatal.requirement}`} : unknown.length?{gate:"HOLD" as GateStatus,maxScore:2,reason:`${unknown.length} critical prerequisite(s) unresolved`}:{gate:"PASS" as GateStatus,maxScore:5,reason:"No essential prerequisite is contradicted or unknown"}}
export function planSearch(searchRunId:string,q:TransformationSearchQuery):ResearchPlan{const phase=(name:string,objective:string,dataSources:string[],expectedOutput:string)=>({name,objective,queries:[`${name}: ${q.mechanismType??"validated mechanisms"} in ${q.therapeuticArea??"all areas"}`],dataSources,expectedOutput});return {searchRunId,phases:[phase("Validate mechanisms","Identify context-specific human validation",["target-disease","regulatory","literature"],"Mechanism assessment proposals"),phase("Find reference assets","Resolve approved and clinical medicines",["drug","clinical-trial"],"Canonical asset links"),phase("Discover constraints","Find clinically meaningful drug-property limitations",["regulatory","clinical-trial","literature"],"Constraint proposals"),phase("Analyze causality","Test causal drug properties and alternatives",["PK/PD","comparative literature"],"Causality proposals"),phase("Match transformations","Apply deterministic compatibility and prerequisites",["transformation taxonomy"],"Transformation proposals"),phase("Try to kill thesis","Search failures and contrary evidence",["literature","trials","companies"],"Contrary analysis"),phase("Assess and cluster","Submit proposals to existing gates and family clustering",["canonical engine"],"Review queue items")],stopConditions:["Human validation confidently below threshold","No meaningful clinical constraint","Causal link is not a transformable property","Critical technical prerequisite contradicted","Therapeutic delta is trivial","Research budget exhausted"]}}
export function enforceBudget(budget:ResearchBudget,usage:{sources:number;searchIterations:number;agentSteps:number;modelCalls:number}){const exceeded:string[]=[];if(usage.sources>=budget.maxSources)exceeded.push("max sources");if(usage.searchIterations>=budget.maxSearchIterations)exceeded.push("max search iterations");if(usage.agentSteps>=budget.maxAgentSteps)exceeded.push("max agent steps");if(usage.modelCalls>=budget.maxModelCalls)exceeded.push("max model calls");return {canContinue:exceeded.length===0,exceeded}}
export function classifyFailedDrug(input:{efficacySignal:boolean;targetEngagement:boolean;limitationEvidence:boolean;mechanismContradicted:boolean;commercialOnly:boolean}):"biology_failure"|"molecule_failure"|"drug_property_constraint"|"commercial_failure"|"unclear"{if(input.mechanismContradicted)return "biology_failure";if(input.commercialOnly)return "commercial_failure";if((input.efficacySignal||input.targetEngagement)&&input.limitationEvidence)return "drug_property_constraint";if(!input.efficacySignal&&input.targetEngagement)return "molecule_failure";return "unclear"}
