import { ConfidenceGrade } from "@/domain/types";
export type ScientificSpecies="human"|"nonhuman_primate"|"mouse"|"other_animal"|"in_vitro"|"unknown";
export interface ScientificSearchQuery{query:string;recordTypes?:string[];limit:number;}
export interface SearchResult{identifier:string;title:string;recordType:string;providerUrl?:string;}
export interface RawScientificRecord{provider:string;providerRecordId:string;providerUrl?:string;recordType:string;rawPayload:Record<string,unknown>;rawText?:string;retrievedAt:string;contentHash:string;}
export interface NormalizedScientificRecord{id:string;rawRecordId:string;normalizedType:string;title:string;abstractOrSummary?:string;publicationDate?:string;identifiers:Record<string,string>;authors:string[];organizations:string[];normalizedPayload:Record<string,unknown>;normalizationVersion:string;}
export interface ScientificDataAdapter{provider:string;search(query:ScientificSearchQuery):Promise<SearchResult[]>;fetch(identifier:string):Promise<RawScientificRecord>;normalize(record:RawScientificRecord):Promise<NormalizedScientificRecord>;}
export interface ExtractedEvidenceClaim{id:string;claimText:string;claimType:string;entities:{type:string;canonicalEntityId?:string;rawName:string}[];context:{indicationId?:string;population?:string;dose?:string;timepoint?:string;comparator?:string};quantitativeData?:{metric:string;value?:number;unit?:string;comparatorValue?:number;statisticalContext?:string}[];evidenceLevel:1|2|3|4|5;directness:"direct"|"indirect"|"inferred";species:ScientificSpecies;sourceLocator?:string;excerpt?:string;extractionConfidence:ConfidenceGrade;evidenceClusterId?:string;}
export interface EntityAlias{entityType:string;entityId:string;canonicalName:string;alias:string;externalIdentifiers:Record<string,string>;confidence:ConfidenceGrade;humanVerified:boolean;}
export interface EntityResolutionResult{status:"resolved"|"unresolved";rawValue:string;candidateEntityId?:string;normalizedName:string;matchReason:string;confidence:ConfidenceGrade;humanVerified:boolean;}
export interface CriticalPrerequisite{requirement:string;isCritical:boolean;status:"supported"|"partially_supported"|"unknown"|"contradicted";confidence:ConfidenceGrade;supportingEvidenceClaimIds:string[];contradictingEvidenceClaimIds:string[];}
export interface ResearchBudget{maxSources:number;maxSearchIterations:number;maxAgentSteps:number;maxModelCalls:number;minimumConfidenceBeforeStopping:ConfidenceGrade;}
export interface ResearchPhase{name:string;objective:string;queries:string[];dataSources:string[];expectedOutput:string;}
export interface ResearchPlan{searchRunId:string;phases:ResearchPhase[];estimatedEntityCount?:number;stopConditions:string[];}
export interface ResearchTask{id:string;agentType:string;objective:string;status:"queued"|"running"|"completed"|"stopped"|"failed";outputSummary?:string;evidenceClaimIds:string[];}
export interface AssessmentProposal{id:string;criterionCode:string;targetEntityId:string;proposedScore:number;proposedConfidence:ConfidenceGrade;baselineConfidence:ConfidenceGrade;confidenceDerivation:string[];rationale:string;supportingEvidenceClaimIds:string[];contradictingEvidenceClaimIds:string[];status:"pending"|"accepted"|"modified"|"rejected";}
export interface ReviewItem{id:string;category:string;entityId:string;priority:"critical"|"high"|"medium"|"low";title:string;summary:string;status:"pending"|"accepted"|"modified"|"rejected"|"deferred";}
export interface ResearchRunDTO{id:string;question:string;researchType:string;status:string;startedAt:string;completedAt?:string;plan:ResearchPlan;budget:ResearchBudget;usage:{sources:number;searchIterations:number;agentSteps:number;modelCalls:number};tasks:ResearchTask[];sources:NormalizedScientificRecord[];claims:ExtractedEvidenceClaim[];resolvedEntities:EntityResolutionResult[];unresolvedGaps:string[];contradictions:string[];proposals:AssessmentProposal[];searchScope:string;illustrative:true;}
