-- Reference taxonomy seed. All scientific examples in the UI are explicitly illustrative.
insert into constraint_types(code,name,sort_order) values
('SAFETY','Safety',10),('SELECTIVITY','Selectivity',20),('PK','Pharmacokinetics',30),('DISTRIBUTION','Distribution',40),('ADMINISTRATION','Administration',50),('EFFICACY_CEILING','Efficacy ceiling',60),('RESISTANCE','Resistance',70),('STABILITY','Stability',80),('DELIVERY','Delivery',90);
insert into constraint_types(parent_id,code,name,sort_order) select id,'SAFETY_ON_TARGET_OFF_TISSUE','On-target, off-tissue safety',11 from constraint_types where code='SAFETY';
insert into constraint_types(parent_id,code,name,sort_order) select id,'SAFETY_OFF_TARGET','Off-target safety',12 from constraint_types where code='SAFETY';
insert into constraint_types(parent_id,code,name,sort_order) select id,'SAFETY_ORGAN_TOXICITY','Organ toxicity',13 from constraint_types where code='SAFETY';
insert into constraint_types(parent_id,code,name,sort_order) select id,'SAFETY_IMMUNE_TOXICITY','Immune toxicity',14 from constraint_types where code='SAFETY';
insert into constraint_types(parent_id,code,name,sort_order) select p.id,v.code,v.name,v.ord from constraint_types p cross join (values ('SELECTIVITY_CELL','Cell selectivity',21),('SELECTIVITY_TISSUE','Tissue selectivity',22),('SELECTIVITY_ISOFORM','Isoform selectivity',23)) v(code,name,ord) where p.code='SELECTIVITY';
insert into constraint_types(parent_id,code,name,sort_order) select p.id,v.code,v.name,v.ord from constraint_types p cross join (values ('PK_SHORT_HALF_LIFE','Short half-life',31),('PK_RAPID_CLEARANCE','Rapid clearance',32),('PK_CMAX_TOXICITY','Cmax toxicity',33),('PK_INADEQUATE_TROUGH','Inadequate trough',34)) v(code,name,ord) where p.code='PK';
insert into constraint_types(parent_id,code,name,sort_order) select p.id,v.code,v.name,v.ord from constraint_types p cross join (values ('DISTRIBUTION_CNS','CNS access',41),('DISTRIBUTION_TUMOR','Tumor access',42),('DISTRIBUTION_INTRACELLULAR','Intracellular distribution',43),('DISTRIBUTION_WRONG_CELL','Wrong-cell distribution',44)) v(code,name,ord) where p.code='DISTRIBUTION';
insert into drug_properties(category,code,name) values ('Exposure','half_life','Half life'),('Exposure','clearance','Clearance'),('Exposure','auc','AUC'),('Exposure','cmax','Cmax'),('Exposure','cmin','Cmin'),('Exposure','bioavailability','Bioavailability'),('Distribution','tissue_distribution','Tissue distribution'),('Distribution','cell_distribution','Cell distribution'),('Distribution','intracellular_exposure','Intracellular exposure'),('Distribution','cns_exposure','CNS exposure'),('Distribution','tumor_exposure','Tumor exposure'),('Binding','affinity','Affinity'),('Binding','avidity','Avidity'),('Binding','selectivity','Selectivity'),('Binding','specificity','Specificity'),('Function','effector_function','Effector function'),('Function','agonism','Agonism'),('Function','antagonism','Antagonism'),('Function','receptor_clustering','Receptor clustering'),('Delivery','internalization','Internalization'),('Delivery','endosomal_escape','Endosomal escape'),('Delivery','cytosolic_release','Cytosolic release'),('Activation','conditional_activation','Conditional activation'),('Activation','local_activation','Local activation');
insert into clinical_advantages(code,category,name) values ('higher_efficacy','Efficacy','Higher efficacy'),('greater_depth_of_response','Efficacy','Greater depth of response'),('longer_duration','Efficacy','Longer duration'),('reduced_toxicity','Safety','Reduced toxicity'),('wider_therapeutic_index','Safety','Wider therapeutic index'),('improved_cell_selectivity','Selectivity','Improved cell selectivity'),('improved_tissue_selectivity','Selectivity','Improved tissue selectivity'),('longer_dosing_interval','Administration','Longer dosing interval'),('iv_to_sc','Administration','IV to SC'),('reduced_treatment_burden','Administration','Reduced treatment burden'),('cns_access','Access','CNS access'),('tumor_access','Access','Tumor access'),('overcome_resistance','Resistance','Overcome resistance'),('enable_new_patient_population','Population','Enable new patient population'),('rescue_unusable_pharmacology','Rescue','Rescue unusable pharmacology');
insert into scoring_frameworks(name,version,description,status) values ('Asset Transformation Engine','v1.0','Gates-first asset and family decision framework','active');
